#Reciept Generator
item1 = input("enter item1:")
price1 = int(input("enter price of item1: "))
item2 = input("enter item2:")
price2 = int(input("enter price of item2: "))
item3 = input("enter item3:")
price3 = int(input("enter price of item3: "))
total = price1 + price2 + price3
print("========================================")
print("KEERTHI MEDICAL STORES")
#end parameter in print()
print("Date: ",end=" ")
#sep parameter in print()
print(11, 6, 2026, sep = "-")
print("========================================")
#f-strings
print(f"{item1} : {price1}")
print(f"{item2} : {price2}")
print(f"{item3} : {price3}")
print("========================================")
print(f"total amount : {total}")
print("========================================")
print("THANK YOU FOR SHOPPING WITH US")
print("VISIT AGAIN!")
